#!/bin/sh

# checkzips - check many ZIP files for errors.
#
# Copyright (C) 2002,2024 Erik Auerswald <auerswal@unix-ag.uni-kl.de>
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

exit_code=0
for file in "$@"; do
  if ! unzip -tqq "${file}" > /dev/null 2>&1; then
    echo Fehler in ZIP-File \""${file}"\"
    exit_code=1
  fi
done
exit "${exit_code}"
