#! /usr/bin/env bash

# ensure_bom_crlf - prepare POSIX text file with UTF-8 data for use on Windows
# Copyright (C) 2022-2024 Erik Auerswald <auerswal@unix-ag.uni-kl.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

set -u

PROG="$(basename "$0")"
VERSION='2024-09-20-02'

print_version()
{
  printf -- '%s version %s\n' "$PROG" "$VERSION"
}

print_copyright()
{
  echo 'Copyright (C) 2022-2024 by Erik Auerswald <auerswal@unix-ag.uni-kl.de>'
}

print_license()
{
  print_copyright
  cat <<EOL

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.  This file is offered as-is,
without any warranty.

EOL
}

print_usage()
{
  cat <<EOU
Usage: $PROG [-r] [[-i] FILE...]
       $PROG {-h | -V | -L}
EOU
}

print_help()
{
  print_usage
  cat <<EOH

Prepare a UTF-8 encoded POSIX text file for use on Windows by ensuring
it starts with the UTF-8 encoded unicode code point U+FEFF "zero-width
no-break space" (the old UCS-2 byte order mark (BOM)), and uses the
<CR><LF> ("\\r\\n") end-of-line character sequence.

Options:
  -h      print this help and exit
  -V      print version information and exit
  -L      print license and exit
  -i      edit all given FILEs in-place
  -r      reverse operation: remove BOM and use <LF> ("\\n") as line ending

Examples:
  $PROG < utf8_encoded_gnu_text > utf8_encoded_windows_text.txt
  $PROG utf8_encoded_gnu_text > utf8_encoded_windows_text.txt
  $PROG -i utf8_encoded_text.txt
EOH
}

INPLACE=0
REVERSE=0
while getopts ':hVLir' OPT; do
  case "$OPT" in
    'h') print_help; exit 0;;
    'V') print_version; exit 0;;
    'L') print_version; print_license; exit 0;;
    'i') INPLACE=1;;
    'r') REVERSE=1;;
    '?') echo "$PROG: ERROR: unknown option '$OPTARG'";
         print_usage; exit 1;;
    *) echo "$PROG: ERROR: getopts() failure"; exit 1;;
  esac
done
shift $((OPTIND - 1))

if test "$REVERSE" -eq 0; then
  SEDSCRIPT='1s/^$/'$'\uFEFF''/
1s/^([^'$'\uFEFF''])/'$'\uFEFF''\1/
s/^$/\r/
s/([^\r])$/\1\r/'
else
  SEDSCRIPT='1s/^'$'\uFEFF''//
s/\r$//'
fi

test "$INPLACE" -eq 1 && test $# -lt 1 && {
  echo "$PROG: ERROR: -i requires a FILE"
  exit 1
}

SEDOPTS='-E'
test "$INPLACE" -eq 1 && SEDOPTS="${SEDOPTS}i"

exec sed "$SEDOPTS" "$SEDSCRIPT" -- "$@"
