#! /bin/sh

# Print externally visible IPv4 and IPv6 addresses.
#
# Copyright (c) 2013-2023 Erik Auerswald <auerswal@unix-ag.uni-kl.de>
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

# get the current IPv4 address using DynDNS
IPv4=$(lynx -dump -nolist http://checkip.dyndns.com/ 2> /dev/null | \
       sed -n -E 's/^.*[^0-9]([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}).*$/\1/p'&)

# transparently get the IPv6 or IPv4 address using icanhazip
IPv46=$(lynx -dump -nolist https://icanhazip.com/ \
       2> /dev/null | sed -nE 's/^[[:space:]]*([0-9a-f:.]+)[[:space:]]*$/\1/p'&)

# get the current IPv6 address using manitu
IPv6=$(lynx -dump -nolist http://wie-ist-meine-ipv6-adresse.de/ \
       2> /dev/null | sed -nE 's/^[[:space:]]*([0-9a-f:]+)[[:space:]]*$/\1/p'&)

wait

test -n "$IPv4" && echo "Current IPv4 address (DynDNS): $IPv4"
test -n "$IPv46" && echo "Current IPv4 or IPv6 address (icanhazip): $IPv46"
test -n "$IPv6" && echo "Current IPv6 address (manitu): $IPv6"

exit 0
