#! /usr/bin/env bash

# Print externally visible IPv4 and IPv6 addresses.
#
# Copyright (c) 2013-2025 Erik Auerswald <auerswal@unix-ag.uni-kl.de>
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

set -u

HAVE_LYNX=''
HAVE_WGET=''
declare -a LYNX WGET
# use lynx to create text from HTML
if command -v lynx >/dev/null; then
  LYNX=('lynx' '-dump' '-nolist')
  HAVE_LYNX='lynx'
  WGET=('lynx' '-dump' '-nolist')
  HAVE_WGET='lynx'
fi
# DynDNS and icanhazip work with wget and curl, too
if command -v wget >/dev/null; then
  WGET=('wget' '-qO-')
  HAVE_WGET='wget'
elif command -v curl >/dev/null; then
  WGET=('curl' '-s')
  HAVE_WGET='curl'
fi

# get the current IPv4 address using DynDNS (returns HTML)
IPv4=''
test -n "$HAVE_WGET" && IPv4=$("${WGET[@]}" http://checkip.dyndns.com/ 2> /dev/null | \
       sed -nE 's/^.*[^0-9]([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}).*$/\1/p'&)

# transparently get the IPv6 or IPv4 address using icanhazip (returns text)
IPv46=''
test -n "$HAVE_WGET" && IPv46=$("${WGET[@]}" https://icanhazip.com/ \
       2> /dev/null | sed -nE 's/^[[:space:]]*([0-9a-f:.]+)[[:space:]]*$/\1/p'&)

# get the current IPv6 address using DynDNS (returns HTML)
IPv6=''
test -n "$HAVE_WGET" && IPv6=$("${WGET[@]}" http://checkipv6.dyndns.com/ \
       2> /dev/null | sed -nE 's/^.*Address: ([0-9a-f:]+).*$/\1/p'&)

wait

test -n "$IPv4" && echo "IPv4 address (DynDNS): $IPv4"
test -n "$IPv6" && echo "IPv6 address (DynDNS): $IPv6"
test -n "$IPv46" && echo "preferred Dual-Stack address (icanhazip): $IPv46"

test -z "$IPv4" && test -z "$IPv46" && test -z "$IPv6" && exit 1
exit 0
