#! /bin/sh

# isascii - check if all input bytes comprise only 7-bit ASCII
# Copyright (C) 2022-2024 Erik Auerswald <auerswal@unix-ag.uni-kl.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

set -u

PROG="$(basename "$0")"
VERSION='2024-09-22-01'

print_version()
{
  printf -- '%s version %s\n' "$PROG" "$VERSION"
}

print_copyright()
{
  echo 'Copyright (C) 2022-2024 Erik Auerswald <auerswal@unix-ag.uni-kl.de>'
}

print_license()
{
  print_copyright
  cat <<EOL

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.  This file is offered as-is,
without any warranty.

EOL
}

print_usage()
{
  cat <<EOU
Usage: $PROG [-v] [FILE...]
       $PROG {-h | -V | -L}
EOU
}

print_help()
{
  print_usage
  cat <<EOH

Check if all input byte values represent 7-bit ASCII code points.
Exit code 0 for all-ASCII input, 1 if a non-ASCII value is found.

Options:
  -h      print this help and exit
  -V      print version information and exit
  -L      print license and exit
  -v      additionally write result information to standard output
EOH
}

VERBOSE=0
while getopts ':hVLv' OPT; do
  case "$OPT" in
    'h') print_help; exit 0;;
    'V') print_version; exit 0;;
    'L') print_version; print_license; exit 0;;
    'v') VERBOSE=1;;
    '?') echo "$PROG: ERROR: unknown option '-$OPTARG'";
         print_usage; exit 1;;
    ':') echo "$PROG: ERROR: argument required for option '-$OPTARG'";
         print_usage; exit 1;;
    *) echo "$PROG: ERROR: getopts() failure"; exit 1;;
  esac
done
shift $((OPTIND - 1))

not_ascii() {
  test "$VERBOSE" -eq 1 && echo 'no'
  exit 1
}

is_ascii() {
  test "$VERBOSE" -eq 1 && echo 'yes'
  exit 0
}

od -An -tx1 -- "$@" | grep -q '[89A-Fa-f][0-9A-Fa-f]' && not_ascii
is_ascii
