#! /bin/sh

# View NFO files.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
#
# Copyright (C) 2011 Erik Auerswald <auerswal@unix-ag.uni-kl.de>

iconv --from 437 -- "$@" | less --raw-control-chars --quit-if-one-screen
