#! /usr/bin/env sh

set -u

# Simplistic Path MTU Discovery using ICMP Echo Request probes.
#
# Copyright (C) 2017-2018 Erik Auerswald <auerswal@unix-ag.uni-kl.de>
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

# Simplistic Path MTU Discovery using ICMP Echo Request probes, may be fooled
# by networks limiting ICMP Echo Request size. Intended use is for PMTUD over
# VPN in broken networks, where standard PMTUD does not work, but the VPN
# hides that the probe packets are ICMP Echo Requests and thus allows the
# script to work.

# Some versions of the Ping program from iputils fragments IPv6 probe
# packets to conform to the local MTU even with the "-M do" option that
# shall prevent local fragmentation. Thus the results of this program
# may be wrong if an IPv6 end point is specified.

VERSION='2018-04-22-01'
PROG="$(basename $0)"
ALGO='binary'
OVERHEAD=28
MIN=68
INCREMENT=10
TABLE='65535 32000 17914 8166 4352 2002 1492 1006 508 296 68'
MAX='auto'
WAIT='.15'
TARGET='8.8.8.8'
PROBETIMEOUT='2'
PINGOPTS="-c1 -Mdo -n -W${PROBETIMEOUT}"

version() { echo "$PROG version $VERSION"; }

copyright()
{
  echo 'Copyright (C) 2017-2018 by Erik Auerswald <auerswal@unix-ag.uni-kl.de>'
}

license()
{
  cat <<EOF
Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.  This file is offered as-is,
without any warranty.
EOF
}

usage() { echo "Usage: $PROG [OPTIONS] [IP | HOSTNAME]"; }

help()
{
  version
  copyright
  usage
  cat <<EOF

Path MTU discovery to given IP / HOSTNAME using ICMP Echo Request probes.
If no IP / HOSTNAME is given, $TARGET is used instead.  The $ALGO search
strategy is used by default.  The upper search limit is automatically
determined by using the current interface MTU of the outgoing interface,
if possible, unless given via option.  The result may be wrong (i.e. too
low) if network or target limit ICMP Echo Request packet size.

Options:
  -h            print this help and exit
  -V            print version and exit
  -L            print license and exit
  -l            use linear search strategy for path MTU discovery
  -b            use binary search strategy for path MTU discovery
  -p            use plateau table based search as suggested in RFC 1191
  -P VALUES     specify alternate plateau table (values separated by whitespace)
  -m MIN        set minimum probe size in bytes (default ${MIN})
  -M MAX        set maximum probe size in bytes (default ${MAX})
  -i INCREMENT  set linear search increment size in bytes (default ${INCREMENT})
  -w WAIT       set time waited between probes (default ${WAIT}s)
  -W TIMEOUT    set probe timeout (default ${PROBETIMEOUT}s)
  -o OVERHEAD   set overhead in bytes added by ping (default ${OVERHEAD})
EOF
}

while getopts ':hVLlbpP:m:M:i:w:W:o:' OPT; do
  case "$OPT" in
    'h') help; exit 0;;
    'V') version; exit 0;;
    'L') version; copyright; license; exit 0;;
    'l') ALGO='linear';;
    'b') ALGO='binary';;
    'p') ALGO='plateau';;
    'P') TABLE="$OPTARG";;
    'm') MIN="$OPTARG";;
    'M') MAX="$OPTARG";;
    'i') INCREMENT="$OPTARG";;
    'w') WAIT="$OPTARG";;
    'W') PROBETIMEOUT="$OPTARG"; PINGOPTS="-c1 -Mdo -n -W${PROBETIMEOUT}";;
    'o') OVERHEAD="$OPTARG";;
    '?') echo "${PROG}: ERROR: unknown option $OPTARG"; exit 1;;
    ':') echo "${PROG}: ERROR: argument required for option $OPTARG"; exit 1;;
    *) echo "${PROG}: ERROR: option $OPT not implemented"; exit 1;;
  esac
done
shift $(($OPTIND - 1))

test $# -eq 1 && { TARGET="$1"; shift; }
test $# -eq 0 || { echo "${PROG}: ERROR: too many arguments"; exit 1; }

# auto_max() attempts to determine the outgoing link's MTU
auto_max()
{
  DEVICE=$(ip route get "$TARGET" | sed -nr 's/^.*dev +([^ ]+) .*$/\1/p')
  ip link show dev "$DEVICE" | sed -nr 's/^.*mtu +([^ ]+) .*$/\1/p'
}

test "x${MAX}x" = 'xautox' && MAX=$(auto_max 2>/dev/null)
MAX=${MAX:-1500}

# error_msg() prints its parameters as a line to STDERR
error_msg()
{
  echo "[!] ERROR: $*" 1>&2
}

# send_probe() has exactly two mandatory parameters:
# 1) the probe size in bytes
# 2) the target IP address or host name
# if the probe is successful, the function will return 0 and print the probe
# size to STDOUT
send_probe()
{
  test $# -eq 2 || {
    error_msg 'send_probe(): wrong number of arguments:' "$#"; return 1;
  }
  S="$1"
  TARGET="$2"
  ping $PINGOPTS -s "$(($S - $OVERHEAD))" "$TARGET" >/dev/null 2>&1 && echo "$S"
}

binary()
{
  local LOW
  local HIGH
  local PROBE

  cat 1>&2 <<EOF
[-] performing binary search IP PMTUD to $TARGET with ICMP Echo Requests
[-] search_low starts at $MIN bytes, search_high starts at $MAX bytes
[-] waiting $WAIT seconds between probes with $PROBETIMEOUT seconds timeout
[-] for unsuccessful probes
EOF

  LOW=$MIN
  HIGH=$MAX
  while test "$LOW" -le "$HIGH"; do
    PROBE=$((($LOW + $HIGH) / 2))
    printf -- '[.] sending %s bytes probe   \r' "$PROBE" 1>&2
    send_probe "$PROBE" "$TARGET"
    if test $? -eq 0; then
      LOW=$(($PROBE+1))
    else
      HIGH=$(($PROBE-1))
    fi
    sleep "$WAIT"
  done | sed -n '$s/^\(.*\)$/[+] IP PMTU is \1 bytes         /p'
  echo '[+] all probes timed out or returned' 1>&2
}

linear()
{
  cat 1>&2 <<EOF
[-] performing linear search IP PMTUD to $TARGET with ICMP Echo Requests
[-] search_low $MIN bytes, search_high $MAX bytes, $INCREMENT byte(s) increments
[-] waiting $WAIT seconds between probes with $PROBETIMEOUT seconds timeout
[-] for unsuccessful probes
EOF

  for S in $(seq "$MIN" "$INCREMENT" "$MAX"); do
    printf -- '[.] sending %s bytes probe\r' "$S" 1>&2
    send_probe "$S" "$TARGET" &
    sleep "$WAIT"
  done | sort -n | sed -n '$s/^\(.*\)$/[+] IP PMTU is \1 bytes/p'
  echo '[+] all probes timed out or returned' 1>&2
}

plateau()
{
  cat 1>&2 <<EOF
[-] performing plateau table based IP PMTUD to $TARGET with ICMP Echo Requests
[-] plateau values used: $TABLE
[-] search_low $MIN bytes, search_high $MAX bytes
[-] waiting $WAIT seconds between probes with $PROBETIMEOUT seconds timeout
[-] for unsuccessful probes
EOF

  for S in $TABLE; do
    test "$S" -gt "$MAX" && continue
    printf -- '[.] sending %s bytes probe   \r' "$S" 1>&2
    send_probe "$S" "$TARGET" &
    sleep "$WAIT"
  done | sort -n | \
    sed -n '$s/^\(.*\)$/[+] plateau estimate for IP PMTU is \1 bytes/p'
  echo '[+] all probes timed out or returned' 1>&2
}

PMTU=$("$ALGO")
test -n "$PMTU" && echo "$PMTU" || {
  echo '[!] could not determine PMTU'
  exit 1
}

# vim:expandtab:
